spring:
  application:
    name: book_server
  
  profiles:
    active: dev
  
  config:
    import: "configserver:"
  
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

      retry:
        initial-interval: 2000  # 2초 간격으로
        max-attempts: 30        # 최대 30번 재시도

      fail-fast: true

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://eureka_server:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
