name: Book Service CI/CD

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  ci-deploy:
    uses: nhnacademy-be12-high-five/.github/.github/workflows/shared-workflow.yml@feat/cicd
    with:
      project-key: team5-book-service
      docker-image: fbxogns123/book-server
      container-name: book_server
      ssh-host: SSH_IP
      ssh-username: SSH_ID
      maven-args: "-B -DskipTests"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKER_USERNAME: DOCKER_USERNAME
      DOCKER_PASSWORD: DOCKER_PASSWORD
      SSH_PASSWORD: SSH_PW
